// Coverage of the CPU verification suites (the riscv-tests each CPU runs, plus random programs): instructions
// and trap causes from the golden model, hardware events from the CPUs' own nets. Prints the tables; --write puts
// them in docs/VERIFICATION.md (between its coverage markers).
//   npx vite-node scripts/coverage.ts [cpu ids…] [--seeds <from>..<to>] [--write]
import { readFileSync, writeFileSync } from 'node:fs';
import { MC_STATES } from '../src/lib/multicycle';
import type { FlatDesign } from '../src/sim/flatten';
import { CAUSE_NAMES, HwCoverage, IsaCoverage, isaInstrs } from '../tests/verify/coverage';
import { CPUS, notApplicable } from '../tests/verify/cpus';
import { fuzzCase, fuzzLanes } from '../tests/verify/fuzz';
import { images } from '../tests/verify/images';
import { cpuJobs, runLanes } from '../tests/verify/run';

const args = process.argv.slice(2);
const opt = (k: string) => (args.includes(k) ? args[args.indexOf(k) + 1] : undefined);
const [from, to] = (opt('--seeds') ?? '1..32').split('..').map(Number);
const ids = args.filter((a, i) => !a.startsWith('--') && !args[i - 1]?.startsWith('--'));
const cpus = CPUS.filter((c) => !ids.length || ids.includes(c.id));

interface Row { id: string; name: string; missing: string[]; claimed: number; traps: Map<number, number>; hw: Map<string, number>; states?: number }
const rows: Row[] = [];
for (const cfg of cpus) {
  const t0 = performance.now();
  const isa = new IsaCoverage(), probes: HwCoverage[] = [];
  const probe = (d: FlatDesign) => { const p = new HwCoverage(d); probes.push(p); return p; };
  for (const b of cpuJobs(cfg, images(cfg.env).filter((i) => !notApplicable(cfg, i.name, i.data.length)), isa)) runLanes(cfg, b.jobs, b.imemK, b.dmemK, probe);
  for (let s = from; s <= to; s += 32) {
    const cases = Array.from({ length: Math.min(32, to - s + 1) }, (_, i) => fuzzCase(cfg, s + i, 60, isa));
    fuzzLanes(cfg, cases, probe);
  }
  const hw = new Map<string, number>();
  for (const p of probes) for (const [k, v] of p.counts) hw.set(k, (hw.get(k) ?? 0) + v);
  const claimed = isaInstrs(cfg.isa);
  const states = cfg.id.startsWith('mc-') ? new Set(probes.flatMap((p) => [...p.states])).size : undefined;
  rows.push({ id: cfg.id, name: cfg.name, claimed: claimed.length, missing: claimed.filter((n) => !isa.instrs.has(n)), traps: isa.traps, hw, states });
  console.log(`${cfg.id.padEnd(15)} instructions ${claimed.length - rows.at(-1)!.missing.length}/${claimed.length}${rows.at(-1)!.missing.length ? ` (missing ${rows.at(-1)!.missing.join(', ')})` : ''}`
    + `  ${[...hw].map(([k, v]) => `${k}: ${v}`).join(', ')}${states !== undefined ? `, states ${states}/${MC_STATES.length}` : ''}  (${((performance.now() - t0) / 1000).toFixed(0)} s)`);
}

const fmt = (n: number) => (n === 0 ? '**0**' : n >= 10_000 ? `${Math.round(n / 1000)}k` : String(n));
const lines: string[] = [];
lines.push(`Generated by \`npx vite-node scripts/coverage.ts --write\` over each CPU's riscv-tests and random programs (seeds ${from}–${to}), `
  + 'counting only while a program runs. Stalls, forwards, flushes and hits are cycles; misses, write-backs, traps and interrupts are '
  + 'events. **0** would mark something the CPU has that no program caused.', '');
lines.push('| CPU | instructions executed | trap causes (golden model) | traps / interrupts in hardware |', '|---|---|---|---|');
for (const r of rows) {
  const traps = [...r.traps].sort((a, b) => a[0] - b[0]).map(([c, n]) => `${CAUSE_NAMES[c] ?? c} ${fmt(n)}`).join(', ');
  const hwTraps = r.hw.has('trap entered') ? `${fmt(r.hw.get('trap entered')!)} / ${fmt(r.hw.get('interrupt taken')!)}` : '—';
  lines.push(`| ${r.name} | ${r.claimed - r.missing.length}/${r.claimed}${r.missing.length ? ` (not: ${r.missing.join(', ')})` : ''} | ${traps || '—'} | ${hwTraps} |`);
}
/** One table per group of events, with the CPUs that have any of them. */
const table = (title: string, cols: string[], extra?: [string, (r: Row) => string]) => {
  const rs = rows.filter((r) => cols.some((c) => r.hw.has(c)) || (extra && extra[1](r) !== '—'));
  if (!rs.length) return;
  const head = [...cols, ...(extra ? [extra[0]] : [])];
  lines.push('', `**${title}**`, '', `| CPU | ${head.join(' | ')} |`, `|---|${head.map(() => '---|').join('')}`);
  for (const r of rs) lines.push(`| ${r.name} | ${[...cols.map((c) => (r.hw.has(c) ? fmt(r.hw.get(c)!) : '—')), ...(extra ? [extra[1](r)] : [])].join(' | ')} |`);
};
table('Pipelines', ['forward M → E', 'forward X → E', 'forward W → E', 'bypass W → D', 'load-use stall', 'FP hazard stall', 'divide stall', 'flush', 'misprediction', 'cache-miss freeze']);
table('Caches', ['D-cache hit', 'D-cache miss', 'write-back', 'I-cache hit', 'I-cache miss']);
table('Multicycle and multi-core', ['memory conflict (both cores)'], ['controller states', (r) => (r.states !== undefined ? `${r.states}/${MC_STATES.length}` : '—')]);
console.log(lines.join('\n'));
if (args.includes('--write')) {
  const file = 'docs/VERIFICATION.md', doc = readFileSync(file, 'utf8');
  const a = '<!-- coverage:begin -->', b = '<!-- coverage:end -->';
  writeFileSync(file, doc.slice(0, doc.indexOf(a) + a.length) + '\n' + lines.join('\n') + '\n' + doc.slice(doc.indexOf(b)));
  console.log(`wrote ${file}`);
}
