// The official riscv-tests on the golden model and on every gate-level RV32 CPU; prints each result and, with
// --write, the pass / fail matrix in docs/VERIFICATION.md (between its riscv-tests markers).
//   npx vite-node scripts/rvtests.ts [cpu ids…] [--test <substring>] [--write]
import { readFileSync, writeFileSync } from 'node:fs';
import { CPUS, issOptions, notApplicable } from '../tests/verify/cpus';
import { imageFile, images, type RvImage } from '../tests/verify/images';
import { cpuJobs, runLanes } from '../tests/verify/run';

const args = process.argv.slice(2);
const filter = args.includes('--test') ? args[args.indexOf('--test') + 1] : '';
const ids = args.filter((a, i) => !a.startsWith('--') && args[i - 1] !== '--test');
const cpus = CPUS.filter((c) => !ids.length || ids.includes(c.id));

/** cpu id → test name → 'pass' | failure text | 'n/a: reason' */
const results = new Map<string, Map<string, string>>();
const t0 = performance.now();
for (const cfg of cpus) {
  const row = new Map<string, string>();
  results.set(cfg.id, row);
  const imgs: RvImage[] = images(cfg.env).filter((i) => i.name.includes(filter));
  for (const img of imgs) {
    const na = notApplicable(cfg, img.name, img.data.length);
    if (na) row.set(img.name, `n/a: ${na}`);
  }
  const t1 = performance.now();
  for (const batch of cpuJobs(cfg, imgs.filter((i) => !row.has(i.name)))) {
    for (const j of batch.jobs) if (!j.golden.pass) row.set(j.img.name, `golden model: ${j.golden.text}`);
    const rs = runLanes(cfg, batch.jobs, batch.imemK, batch.dmemK);
    batch.jobs.forEach((j, i) => { if (!row.has(j.img.name)) row.set(j.img.name, rs[i].pass ? 'pass' : rs[i].text); });
  }
  const fails = [...row].filter(([, v]) => v !== 'pass' && !v.startsWith('n/a'));
  console.log(`${cfg.id.padEnd(15)} ${[...row.values()].filter((v) => v === 'pass').length} pass, ${fails.length} fail, ${[...row.values()].filter((v) => v.startsWith('n/a')).length} n/a  (${((performance.now() - t1) / 1000).toFixed(1)} s)`);
  for (const [n, v] of fails) console.log(`    ${n}: ${v}`);
}
console.log(`total ${((performance.now() - t0) / 1000).toFixed(0)} s`);

if (args.includes('--write')) {
  const suites = ['rv32ui', 'rv32um', 'rv32uf', 'rv32ua', 'rv32mi'];
  const lines: string[] = [];
  const rev = imageFile('p').revision;
  lines.push(`Generated by \`npx vite-node scripts/rvtests.ts --write\` from riscv-tests [${rev['riscv-tests'].slice(0, 7)}](https://github.com/riscv-software-src/riscv-tests/commit/${rev['riscv-tests']}) (env ${rev.env.slice(0, 7)}), built with ${imageFile('p').toolchain}.`, '');
  lines.push('| CPU | env | ' + suites.join(' | ') + ' |', '|---|---|' + suites.map(() => '---|').join(''));
  for (const cfg of cpus) {
    const row = results.get(cfg.id)!;
    const cell = (suite: string) => {
      const rs = [...row].filter(([n]) => n.startsWith(`${suite}-`));
      const run = rs.filter(([, v]) => !v.startsWith('n/a'));
      if (!run.length) return '—';
      const pass = run.filter(([, v]) => v === 'pass').length;
      return pass === run.length ? `✅ ${pass}/${run.length}` : `❌ ${pass}/${run.length}`;
    };
    lines.push(`| ${cfg.name} | ${cfg.env} | ${suites.map(cell).join(' | ')} |`);
  }
  lines.push('', 'Not run (n/a), by reason:', '');
  const reasons = new Map<string, Map<string, string[]>>();
  for (const cfg of cpus) for (const [n, v] of results.get(cfg.id)!) {
    if (!v.startsWith('n/a: ')) continue;
    const r = v.slice(5), m = reasons.get(r) ?? new Map<string, string[]>();
    reasons.set(r, m);
    m.set(n, [...(m.get(n) ?? []), cfg.id]);
  }
  /** The CPUs a reason applies to: all, all but a few, or a list. */
  const who = (ids: string[]) => {
    const rest = cpus.map((c) => c.id).filter((id) => !ids.includes(id));
    return !rest.length ? 'every CPU' : rest.length < ids.length ? `every CPU but ${rest.join(', ')}` : ids.join(', ');
  };
  for (const [r, m] of reasons) {
    const tests = [...m.keys()], first = m.get(tests[0])!;
    const same = tests.every((t) => m.get(t)!.join() === first.join());
    lines.push(`- ${r}: ${tests.map((t) => `\`${t}\``).join(', ')}${same ? ` (${who(first)})` : ''}`);
  }
  const fails = cpus.flatMap((c) => [...results.get(c.id)!].filter(([, v]) => v !== 'pass' && !v.startsWith('n/a')).map(([n, v]) => `- ${c.name}: \`${n}\` ${v}`));
  lines.push('', fails.length ? 'Failures:' : 'No failures.', '', ...fails);
  const file = 'docs/VERIFICATION.md', doc = readFileSync(file, 'utf8');
  const a = '<!-- riscv-tests:begin -->', b = '<!-- riscv-tests:end -->';
  writeFileSync(file, doc.slice(0, doc.indexOf(a) + a.length) + '\n' + lines.join('\n') + '\n' + doc.slice(doc.indexOf(b)));
  console.log(`wrote ${file}`);
}
