// Synthesizable Verilog for the whole hierarchy below a component, for real tools (Yosys, OpenROAD):
// one module per ComponentDef, NAND as a continuous assignment, flip-flops (`ff`: the master–slave
// DFF, a user chip ticked as one) as clocked processes (a synthesis tool cannot use cross-coupled
// NAND loops as storage), constant ties as 1'b0 / 1'b1, splitters and mergers as bit slices, a part
// with its own `hdl.synth` body (a large RAM / ROM: a `reg mem [..]` array) as that body. Plain
// Verilog-2005 with identifiers sanitized, so any tool reads it.

import { type ComponentDef, isExternal, isSwitchPrim, netlistOf, parseEnd, type PortDef } from './types';

const KEYWORDS = new Set(('always and assign automatic begin buf bufif0 bufif1 case casex casez cell cmos config deassign default defparam design disable edge else end endcase endconfig endfunction endgenerate endmodule endprimitive endspecify endtable endtask event for force forever fork function generate genvar highz0 highz1 if ifnone incdir include initial inout input instance integer join large liblist library localparam macromodule medium module nand negedge nmos nor noshowcancelled not notif0 notif1 or output parameter pmos posedge primitive pull0 pull1 pulldown pullup pulsestyle_onevent pulsestyle_ondetect rcmos real realtime reg release repeat rnmos rpmos rtran rtranif0 rtranif1 scalared showcancelled signed small specify specparam strong0 strong1 supply0 supply1 table task time tran tranif0 tranif1 tri tri0 tri1 triand trior trireg unsigned use uwire vectored wait wand weak0 weak1 while wire wor xnor xor logic bit byte int priority unique final do')
  .split(' '));

export function ident(s: string, fallback: string): string {
  let t = s.replace(/[^A-Za-z0-9_]/g, '_');
  if (!t || /^[0-9]/.test(t) || /^_+$/.test(t)) t = fallback;
  if (KEYWORDS.has(t)) t += '_';
  return t;
}

const range = (w: number) => (w > 1 ? `[${w - 1}:0] ` : '');

/** A flip-flop (`ff`) whose only ports are d, q, clk (and en): exported as a process. */
const ffLeaf = (def: ComponentDef) => {
  const ff = def.ff;
  return ff && def.ports.every((p) => [ff.d, ff.q, ff.clk, ff.en].includes(p.name)) ? ff : undefined;
};

/** Leaves of the exported hierarchy: written as behaviour, not expanded. */
function leafBody(def: ComponentDef): string[] | null {
  if (def.id === 'nand') return ['  assign y = ~(a & b);'];
  const ff = ffLeaf(def);
  if (ff) {
    const n = (port: string) => portNameOf(def, port);
    return [`  always @(posedge ${n(ff.clk)}) ${ff.en ? `if (${n(ff.en)}) ` : ''}${n(ff.q)} <= ${n(ff.d)};`];
  }
  if (def.id === 'tie0' || def.id === 'tie1') return [`  assign ${def.ports[0].name} = 1'b${def.id === 'tie1' ? 1 : 0};`];
  // its own synthesizable body (a large memory as an array), the structure below it not exported
  if (def.hdl?.synth) return def.hdl.synth;
  return null;
}

export interface ExportResult { verilog: string; modules: number; top: string }

export function synthVerilog(root: ComponentDef, topName?: string): ExportResult {
  const names = new Map<ComponentDef, string>();
  const used = new Set<string>();
  const order: ComponentDef[] = [];
  const nameOf = (d: ComponentDef) => {
    let n = names.get(d);
    if (!n) {
      n = d === root && topName ? topName : ident(d.id, 'm');
      if (d.id === 'nand') n = 'nand2_cell';
      while (used.has(n)) n += '_';
      used.add(n);
      names.set(d, n);
    }
    return n;
  };
  const visit = (d: ComponentDef) => {
    if (names.has(d) && order.includes(d)) return;
    nameOf(d);
    if (!leafBody(d)) {
      if (isSwitchPrim(d)) {
        throw new Error(`${d.name}: transistors, rails, resistors and capacitors are not synthesizable (export the exact structure instead)`);
      }
      const nl = netlistOf(d);
      if (!nl) throw new Error(`${d.id}: no netlist and no behaviour for export`);
      for (const i of nl.instances) if (i.def.prim !== 'alias' && !isExternal(i.def)) visit(i.def);
    }
    if (!order.includes(d)) order.push(d);
  };
  visit(root);

  const out: string[] = [`// Generated by MOSFET → RISC-V from the schematics. Top: ${nameOf(root)}`, ''];
  for (const d of order) out.push(moduleText(d, nameOf), '');
  return { verilog: out.join('\n'), modules: order.length, top: nameOf(root) };
}

function moduleText(def: ComponentDef, nameOf: (d: ComponentDef) => string): string {
  const portName = new Map<string, string>();
  const used = new Set<string>();
  for (const p of def.ports) {
    let n = ident(p.name, 'p');
    while (used.has(n)) n += '_';
    used.add(n);
    portName.set(p.name, n);
  }
  const leaf = leafBody(def);
  const isReg = (p: PortDef) => !!leaf && p.name === ffLeaf(def)?.q;
  const lines: string[] = [];
  lines.push(`module ${nameOf(def)} (${def.ports.map((p) => portName.get(p.name)).join(', ')});`);
  for (const p of def.ports) lines.push(`  ${p.dir === 'in' ? 'input' : p.dir === 'out' ? 'output' : 'inout'} ${isReg(p) ? 'reg ' : ''}${range(p.width)}${portName.get(p.name)};`);
  if (leaf) {
    lines.push(...leaf, 'endmodule');
    return lines.join('\n');
  }
  const nl = netlistOf(def)!;
  const widthOf = (end: string): number => {
    const { inst, port } = parseEnd(end);
    if (inst === null) return def.ports.find((p) => p.name === port)!.width;
    return nl.instances.find((i) => i.name === inst)!.def.ports.find((p) => p.name === port)!.width;
  };
  const netName: string[] = [];
  const assigns: string[] = [];
  nl.nets.forEach((net, i) => {
    const own = net.ends.map(parseEnd).filter((e) => e.inst === null).map((e) => e.port);
    if (own.length) {
      // a net touching several ports: the first input (or the first port) drives the others
      const drv = own.find((p) => def.ports.find((q) => q.name === p)!.dir === 'in') ?? own[0];
      netName.push(portName.get(drv)!);
      for (const o of own) if (o !== drv) assigns.push(`  assign ${portName.get(o)} = ${portName.get(drv)};`);
      return;
    }
    let n = ident(net.name ?? '', `n${i}`);
    if (n === `n${i}` || used.has(n)) n = `${n === `n${i}` ? '' : `${n}_`}n${i}`;
    while (used.has(n)) n += '_';
    used.add(n);
    lines.push(`  wire ${range(widthOf(net.ends[0]))}${n};`);
    netName.push(n);
  });
  const endNet = new Map<string, string>();
  nl.nets.forEach((net, i) => net.ends.forEach((e) => endNet.set(e, netName[i])));
  const instUsed = new Set<string>(used);
  for (const inst of nl.instances) {
    const c = inst.def;
    const conn = (port: string) => endNet.get(`${inst.name}.${port}`);
    if (c.prim === 'alias') {
      // pure wiring: one assign per aliased bit, from the input side to the output side
      const width = (port: string) => c.ports.find((p) => p.name === port)!.width;
      const dir = (port: string) => c.ports.find((p) => p.name === port)!.dir;
      const bitOf = (port: string, b: number) => { const n = conn(port); return n ? (width(port) > 1 ? `${n}[${b}]` : n) : null; };
      for (const [pa, ba, pb, bb] of c.alias ?? []) {
        const [src, sb, dst, db] = dir(pa) === 'in' ? [pa, ba, pb, bb] : [pb, bb, pa, ba];
        if (dir(src) !== 'in' || dir(dst) !== 'out') continue;
        const from = bitOf(src, sb), to = bitOf(dst, db);
        if (from && to) assigns.push(`  assign ${to} = ${from};`);
      }
      continue;
    }
    if (isExternal(c)) {
      lines.push(`  // ${inst.name}: ${c.name} (an input from the sandbox, not hardware): its outputs are left undriven`);
      continue;
    }
    let iname = ident(inst.name, 'u');
    while (instUsed.has(iname)) iname += '_';
    instUsed.add(iname);
    const args = c.ports.map((p) => `.${portNameOf(c, p.name)}(${conn(p.name) ?? ''})`);
    lines.push(`  ${nameOf(c)} ${iname} (${args.join(', ')});`);
  }
  lines.push(...assigns, 'endmodule');
  return lines.join('\n');
}

/** Port names as sanitized in the child's module (deterministic: same rule as moduleText). */
function portNameOf(def: ComponentDef, port: string): string {
  const used = new Set<string>();
  for (const p of def.ports) {
    let n = ident(p.name, 'p');
    while (used.has(n)) n += '_';
    used.add(n);
    if (p.name === port) return n;
  }
  return port;
}
